version '3'

services:
 calc_service:
   build: .
   image: calc
   container_name: calc
   ports:
     - 4000:4000
   volumes:
     - ./server_data:/app/MSC_Server
     - /home/maxrev/certs:/certs
   environment:
     - VIRTUAL_HOST=calc.nuwm.edu.ua 
     - VIRTUAL_PORT=4000
     - LETSENCRYPT_HOST=calc.nuwm.edu.ua 
     - LETSENCRYPT_EMAIL=tea_ak16@nuwm.edu.ua
   networks:
     - nuwee-api

networks:
  nuwee-api: 
   external: true